language: minimal

jobs:
  include:
    - os: linux
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-manylinux2010_x86_64.sh
        - ls -l dist/
    - os: osx
      language: shell
      sudo: required
      install:
        - brew cask install graalvm/tap/graalvm-ce-java11
        - export PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/bin:"$PATH"
        - gu install native-image
        - brew install swig
        - pip3 install twine
        - pyenv install 3.6.9
        - pyenv install 3.7.5
        - pyenv install 3.8.0
      script:
        - travis/build-macos.sh
        - ls -l dist/
    - os: windows
      language: shell
      install:
        - choco install python --version=3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install twine
        - choco install pyenv-win
        - export PATH="C:\Users\travis\.pyenv\pyenv-win\bin:C:\Users\travis\.pyenv\pyenv-win\shims:$PATH"
        - pyenv install -q 3.6.8-amd64
        - pyenv install -q 3.7.5-amd64
        - pyenv install -q 3.8.0-amd64
        - choco install maven --version=3.6.3
        - export PATH="/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin:$PATH"
        - choco install graalvm --version=20.0.0
        - export PATH="/c/Program Files/GraalVM/graalvm-ce-java11-20.0.0/bin:$PATH"
        - choco install swig --version=4.0.1
        - gu.cmd install native-image
      script:
        - travis/build.bat
        - ls -l dist/
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  # Do not delete generated build files (i.e. wheels)
  skip_cleanup: true
  # Do not attempt to upload to PyPI an already uploaded wheel
  skip_existing: true
  user: __token__
  # PyPI password should be stored on Travis CI as a secret env variable named PYPI_PASSWORD
  on:
    tags: true
