language: minimal

jobs:
  include:
    - os: linux
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-manylinux2010_x86_64.sh
        - ls -l dist/
    - os: osx
      language: shell
      env: HOMEBREW_NO_AUTO_UPDATE=1
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew      
      sudo: required
      install:
        - brew cask install graalvm/tap/graalvm-ce-java11
        - export JAVA_HOME=$(/usr/libexec/java_home -v 11)
        - export PATH=$JAVA_HOME/bin:$PATH
        - gu install native-image
        - brew install swig
        - pip3 install twine
        - pyenv install --list
        - pyenv install 3.6.9
        - pyenv install 3.7.5
        - pyenv install 3.8.0
        - pyenv install 3.9.0
      script:
        - travis/build-macos.sh
        - ls -l dist/
    - os: windows
      language: shell
      install:
        - choco install pyenv-win
        - export PATH="C:\Users\travis\.pyenv\pyenv-win\bin:C:\Users\travis\.pyenv\pyenv-win\shims:$PATH"
        - pyenv install --list
        - pyenv install -q 3.6.8
        - pyenv install -q 3.7.7
        - pyenv install -q 3.8.2
        - choco install maven --version=3.6.3
        - export PATH="/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin:$PATH"
        - choco install graalvm --version=20.2.0
        - export PATH="/c/Program Files/GraalVM/graalvm-ce-java11-20.2.0/bin:$PATH"
        - choco install swig --version=4.0.1
        - gu.cmd install native-image
      script:
        - travis/build.bat
        - ls -l dist/
      deploy:
        # https://github.com/travis-ci/dpl/issues/1009
        provider: script
        script: bash ./travis/deploy.sh
        # Do not delete generated build files (i.e. wheels)
        skip_cleanup: true
        # Do not attempt to upload to PyPI an already uploaded wheel
        skip_existing: true
        on:
          tags: true

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  # Do not delete generated build files (i.e. wheels)
  skip_cleanup: true
  # Do not attempt to upload to PyPI an already uploaded wheel
  skip_existing: true
  user: __token__
  # PyPI password should be stored on Travis CI as a secret env variable named PYPI_PASSWORD
  on:
    tags: true
